### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [MSMK2/prj-rev-bwfs-dasmoto#3]
Instead of having to write `font-weight: bold;` 3 times here, you could specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2, .pricing {
  font-weight: bold;
}
```

https://github.com/MSMK2/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts%20and%20Crafts/resources/css/style.css
